"""Split LESSON_PLANS.md into per-chapter chapters/chXX-*/LESSON.md files.

Reads the master file, finds each '## Chapter N — ...' section, and writes it
into the matching chapter folder. Idempotent — re-runnable.
"""
import sys, io, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from pathlib import Path

ROOT = Path(__file__).parent.resolve()
MASTER = ROOT / 'LESSON_PLANS.md'

CHAPTER_SLUGS = {
    1: 'ch01-landscape', 2: 'ch02-pixel-ops', 3: 'ch03-classical-features',
    4: 'ch04-camera-geometry', 5: 'ch05-cnns', 6: 'ch06-training',
    7: 'ch07-detection', 8: 'ch08-segmentation', 9: 'ch09-vit',
    10: 'ch10-self-supervised', 11: 'ch11-clip', 12: 'ch12-diffusion',
    13: 'ch13-vlm', 14: 'ch14-document-ai-agents', 15: 'ch15-video',
    16: 'ch16-3d-gaussian-splatting', 17: 'ch17-vla-robotics',
    18: 'ch18-domains', 19: 'ch19-edge-deployment', 20: 'ch20-mlops-future',
}

HEADER = """<!-- This file is auto-generated by split_lesson_plans.py from LESSON_PLANS.md.
     Edit the master file and re-run, OR edit here and back-port if you prefer.
     Do not duplicate content; see ../../LESSON_PLANS.md for cross-chapter context. -->

"""


def main():
    text = MASTER.read_text(encoding='utf-8')

    # Find all chapter headings: "## Chapter N — ..."
    pattern = re.compile(r'^## Chapter (\d+) — .*$', re.MULTILINE)
    matches = list(pattern.finditer(text))
    if not matches:
        print('No chapter headings found.')
        return

    # Append a sentinel at the end for slicing
    end_anchor = re.search(r'^## How to use these lesson plans', text, re.MULTILINE)
    if not end_anchor:
        print('Tail anchor not found; using end-of-file.')
        end_pos = len(text)
    else:
        end_pos = end_anchor.start()

    written = 0
    for i, m in enumerate(matches):
        ch_num = int(m.group(1))
        slug = CHAPTER_SLUGS.get(ch_num)
        if not slug:
            print(f'  skip ch {ch_num} — no slug mapping')
            continue
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else end_pos
        body = text[start:end].rstrip() + '\n'

        out = ROOT / 'chapters' / slug / 'LESSON.md'
        out.write_text(HEADER + body, encoding='utf-8')
        print(f'  wrote: {out.relative_to(ROOT)}')
        written += 1

    print(f'\n✓ Split into {written} per-chapter LESSON.md files.')


if __name__ == '__main__':
    main()
